### ISSUE TITLE
Non-recoverable error with rails and S=-3

### ISSUE THREAD

**Issue by EMeindertsma** [sparr/factorio-mod-entity-symmetry#12]
```The mod Entity Symmetry (2.1.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event entity-symmetry::on_built_entity (ID 6)
__entity-symmetry__/control.lua:624: attempt to index local 'new_entity' (a nil value)
stack traceback:
	__entity-symmetry__/control.lua:624: in function 'on_altered_entity'
	__entity-symmetry__/control.lua:720: in function <__entity-symmetry__/control.lua:720>
```
[log file](https://github.com/user-attachments/files/17603849/factorio-current.log)

To reproduce the issue (error when pasting/building):
0. In editor mode with cheat mode on. Factorio version 2.0.13
1. build a Symmetry Center with the specified settings (C=1, D=64, R=1, S=-3)
2. Build a rail piece (should be mirrored by four)
3. Destroy the piece you built (note that the other pieces are not destroyed, which is already a bug)
4. Rebuild the destroyed piece
The game now crashes.

Cutting and re-pasting the Symmetry Center with some rails around it gives the same crash. Sometimes half of the rails are built fully, while half are left as blueprints when the game crashes (The ones in the upper half plane are fully built).

I first got the error message when using undo twice after pasting some rails, with the same settings for the Symmetry Center, so it might be related to https://github.com/sparr/factorio-mod-entity-symmetry/issues/11

**Comment by sparr** [comment]
Fixed in latest release. Thanks for the report.
