### ISSUE TITLE
Entity deletion not reflected for some entities

### ISSUE THREAD

**Issue by EBTheHero** [sparr/factorio-mod-entity-symmetry#9]
When placing some entities, like a chest, the entity is mirrored on the other side of the symmetry center. But when removing the entity, the changes are not reflected to the other sides.

This affects a good amount of entities (like assemblers) while some entities work fine (like belts).

Tested in a "sandbox" scenario with entity-symmetry 1.2.1 and base game 1.1.94. The default settings were used (C = -1, D = 64, R = 0, S = 4)

An non exaustive list of items which deletion does not work:
- All 3 assemblers
- All 3 furnaces
- Labs
- Beacons
- All 4 electric poles
- Accumulators
- Steam Engine
- Steam turbine
- Heat pipes
- Walls
- Roboports
- Gun and laser turrets (but not flamethrowers)
- Radar
- Power switch (but none of the three combinators)
- Lamp
- Solar panel
- Pipe (but not underground pipes)
- All chests

**Comment by sparr** [comment]
Thank you for this report. I suspect I broke something while getting simple-entity-with-owner to work. I will test more thoroughly and get this fixed.

**Comment by sparr** [comment]
Fixed in b3f1fd84ffbcd395713f938dc1bff8cc03f83364

**Comment by sparr** [comment]
PS: What all those entities have in common is that they don't rotate.

**Comment by EBTheHero** [comment]
The mystery is solved!
Thank you! I tested it on my side!
